### ISSUE TITLE
trackSearchの引数は properties: any 

### ISSUE THREAD

**Issue by atake831** [scrpgil/repro#1]
http://docs.repro.io/ja/dev/sdk/tracking.html?highlight=api#id4
公式docsによるとtrackSearchに関して、こちらproperties: stringではなく、properties: anyに変更する必要がありそうです。
プルリクを作成しようと思ったのですが、build前のindex.tsがない？状態なのですが、どのように開発・プルリクを送るべきでしょうか？

**Comment by scrpgil** [comment]
ありがとうございます！そして、バグがあって申し訳ないです。
index.tsを以下のリポジトリにアップしましたので確認お願いします。
https://github.com/scrpgil/ionic-native

「src/@ionic-native/plugins/repro/index.ts」にbuild前のファイルがありますので、これを修正して、npm run build reproとやるとラッパーファイルのjsができます。
そちらをプルリクしてもらえれば...。

**Comment by atake831** [comment]
https://github.com/scrpgil/repro/pull/2
プルリクを作成いたしました。ご確認いただければ幸いです。

**Comment by scrpgil** [comment]
ありがとうございます。
変更内容を確認してマージしました。
